In [1]:
def unpickle(file):
    import pickle
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
    return dict

In [2]:
file='C://Users/HP/Desktop/cipher10/cifar-10-batches-py/data_batch_1'

In [3]:
dataset=unpickle(file)
x=dataset[b'data']
y=dataset[b'labels']


In [4]:
x

array([[ 59,  43,  50, ..., 140,  84,  72],
       [154, 126, 105, ..., 139, 142, 144],
       [255, 253, 253, ...,  83,  83,  84],
       ...,
       [ 71,  60,  74, ...,  68,  69,  68],
       [250, 254, 211, ..., 215, 255, 254],
       [ 62,  61,  60, ..., 130, 130, 131]], dtype=uint8)

In [5]:
y

[6,
 9,
 9,
 4,
 1,
 1,
 2,
 7,
 8,
 3,
 4,
 7,
 7,
 2,
 9,
 9,
 9,
 3,
 2,
 6,
 4,
 3,
 6,
 6,
 2,
 6,
 3,
 5,
 4,
 0,
 0,
 9,
 1,
 3,
 4,
 0,
 3,
 7,
 3,
 3,
 5,
 2,
 2,
 7,
 1,
 1,
 1,
 2,
 2,
 0,
 9,
 5,
 7,
 9,
 2,
 2,
 5,
 2,
 4,
 3,
 1,
 1,
 8,
 2,
 1,
 1,
 4,
 9,
 7,
 8,
 5,
 9,
 6,
 7,
 3,
 1,
 9,
 0,
 3,
 1,
 3,
 5,
 4,
 5,
 7,
 7,
 4,
 7,
 9,
 4,
 2,
 3,
 8,
 0,
 1,
 6,
 1,
 1,
 4,
 1,
 8,
 3,
 9,
 6,
 6,
 1,
 8,
 5,
 2,
 9,
 9,
 8,
 1,
 7,
 7,
 0,
 0,
 6,
 9,
 1,
 2,
 2,
 9,
 2,
 6,
 6,
 1,
 9,
 5,
 0,
 4,
 7,
 6,
 7,
 1,
 8,
 1,
 1,
 2,
 8,
 1,
 3,
 3,
 6,
 2,
 4,
 9,
 9,
 5,
 4,
 3,
 6,
 7,
 4,
 6,
 8,
 5,
 5,
 4,
 3,
 1,
 8,
 4,
 7,
 6,
 0,
 9,
 5,
 1,
 3,
 8,
 2,
 7,
 5,
 3,
 4,
 1,
 5,
 7,
 0,
 4,
 7,
 5,
 5,
 1,
 0,
 9,
 6,
 9,
 0,
 8,
 7,
 8,
 8,
 2,
 5,
 2,
 3,
 5,
 0,
 6,
 1,
 9,
 3,
 6,
 9,
 1,
 3,
 9,
 6,
 6,
 7,
 1,
 0,
 9,
 5,
 8,
 5,
 2,
 9,
 0,
 8,
 8,
 0,
 6,
 9,
 1,
 1,
 6,
 3,
 7,
 6,
 6,
 0,
 6,
 6,
 1,
 7,
 1,
 5,
 8,
 3,
 6,
 6,
 8,
 6,
 8,
 4,
 6,
 6,


In [6]:
len(x)

10000

In [7]:
len(y)


10000

In [8]:
import numpy as np
for i in range(2,6):
    file='C://Users/HP/Desktop/cipher10/cifar-10-batches-py/data_batch_'+str(i)
    dataset=unpickle(file)
    x=np.concatenate((x,dataset[b'data']),axis=0)
    for j in dataset[b'labels']:
        y.append(j)

In [9]:
len(x)

50000

In [10]:
len(y)

50000

In [11]:
## available output names.
namesofop=np.array(['airplane','automobile','bird','cat','deer','dog','frog','horse','ship','truck'])

In [12]:
x

array([[ 59,  43,  50, ..., 140,  84,  72],
       [154, 126, 105, ..., 139, 142, 144],
       [255, 253, 253, ...,  83,  83,  84],
       ...,
       [ 35,  40,  42, ...,  77,  66,  50],
       [189, 186, 185, ..., 169, 171, 171],
       [229, 236, 234, ..., 173, 162, 161]], dtype=uint8)

In [13]:
## feature scale
from sklearn import preprocessing
scalar=preprocessing.StandardScaler()
scalar.fit(x)
x=scalar.transform(x)
x

array([[-0.97682401, -1.20290054, -1.12196343, ...,  0.40326438,
        -0.45860013, -0.6414024 ],
       [ 0.3172399 , -0.05715424, -0.36061052, ...,  0.38785462,
         0.43080648,  0.44823767],
       [ 1.69303417,  1.69597564,  1.68812096, ..., -0.47509172,
        -0.47393472, -0.45979572],
       ...,
       [-1.30374542, -1.24431306, -1.23270567, ..., -0.56755025,
        -0.73462287, -0.97434797],
       [ 0.79400029,  0.7710961 ,  0.7468119 , ...,  0.8501473 ,
         0.87550978,  0.85685269],
       [ 1.33886931,  1.46130471,  1.42510813, ...,  0.91178633,
         0.73749841,  0.70551379]])

In [ ]:
##use random forest

In [14]:
## use svm
from sklearn.svm import SVC
clf=SVC()
clf.fit(x,y)

SVC()

In [15]:
## collecting the test dataset
file='C://Users/HP/Desktop/cipher10/cifar-10-batches-py/test_batch'
dataset=unpickle(file)
x=dataset[b'data']
x=scalar.transform(x)
y=dataset[b'labels']

In [16]:
## random forest score
clf.score(x,y)

0.5481

In [18]:
ypred=clf.predict(x)

In [43]:
ypredlist=list(ypred)

In [49]:
for i in range(len(ypredlist)):
    if(ypredlist[i]==0):
        ypredlist[i]='airplane'

    elif(ypredlist[i]==1):
        ypredlist[i]='automobile'

    elif(ypredlist[i]==2):
        ypredlist[i]='bird'
        
    elif(ypredlist[i]==3):
        ypredlist[i] = "cat"
        
    elif(ypredlist[i]==4):
        ypredlist[i]='deer'
        
    elif(ypredlist[i]==5):
        ypredlist[i]='dog'
        
    elif(ypredlist[i]==6):
        ypredlist[i]='frog'
        
    elif(ypredlist[i]==7):
        ypredlist[i]='horse'
        
    elif(ypredlist[i]==8):
        ypredlist[i]='ship'
        
    else:
        ypredlist[i]='truck'

In [44]:
ypredlist

[3,
 8,
 8,
 0,
 4,
 6,
 3,
 6,
 2,
 1,
 8,
 9,
 1,
 7,
 9,
 8,
 5,
 3,
 8,
 6,
 9,
 0,
 0,
 9,
 4,
 6,
 4,
 0,
 9,
 6,
 6,
 4,
 4,
 5,
 9,
 1,
 6,
 9,
 9,
 5,
 4,
 6,
 3,
 4,
 0,
 9,
 5,
 8,
 4,
 6,
 9,
 8,
 6,
 3,
 8,
 8,
 5,
 6,
 3,
 2,
 7,
 3,
 6,
 9,
 6,
 2,
 1,
 2,
 3,
 9,
 2,
 6,
 8,
 8,
 0,
 2,
 9,
 3,
 3,
 8,
 8,
 1,
 1,
 5,
 2,
 7,
 3,
 8,
 8,
 9,
 0,
 4,
 8,
 6,
 4,
 3,
 4,
 0,
 0,
 7,
 4,
 4,
 6,
 3,
 1,
 1,
 3,
 6,
 3,
 7,
 4,
 2,
 2,
 4,
 9,
 1,
 0,
 9,
 2,
 5,
 8,
 4,
 1,
 2,
 0,
 1,
 8,
 3,
 3,
 0,
 4,
 1,
 9,
 9,
 1,
 2,
 9,
 7,
 2,
 8,
 2,
 5,
 6,
 5,
 8,
 2,
 6,
 5,
 7,
 5,
 1,
 9,
 6,
 8,
 4,
 5,
 2,
 8,
 3,
 4,
 0,
 7,
 5,
 6,
 9,
 7,
 8,
 6,
 7,
 0,
 9,
 7,
 0,
 8,
 9,
 9,
 8,
 7,
 3,
 9,
 0,
 7,
 6,
 2,
 2,
 8,
 6,
 2,
 6,
 0,
 5,
 3,
 7,
 1,
 7,
 2,
 8,
 0,
 7,
 8,
 3,
 9,
 8,
 7,
 1,
 5,
 0,
 4,
 7,
 8,
 2,
 1,
 3,
 7,
 8,
 0,
 1,
 9,
 0,
 7,
 7,
 6,
 9,
 6,
 9,
 9,
 3,
 2,
 3,
 2,
 5,
 1,
 1,
 2,
 8,
 0,
 6,
 0,
 3,
 5,
 1,
 9,
 7,
 9,
 0,
 1,
 7,
 0,
 5,
 1,


In [50]:
ypredlist

['cat',
 'ship',
 'ship',
 'airplane',
 'deer',
 'frog',
 'cat',
 'frog',
 'bird',
 'automobile',
 'ship',
 'truck',
 'automobile',
 'horse',
 'truck',
 'ship',
 'dog',
 'cat',
 'ship',
 'frog',
 'truck',
 'airplane',
 'airplane',
 'truck',
 'deer',
 'frog',
 'deer',
 'airplane',
 'truck',
 'frog',
 'frog',
 'deer',
 'deer',
 'dog',
 'truck',
 'automobile',
 'frog',
 'truck',
 'truck',
 'dog',
 'deer',
 'frog',
 'cat',
 'deer',
 'airplane',
 'truck',
 'dog',
 'ship',
 'deer',
 'frog',
 'truck',
 'ship',
 'frog',
 'cat',
 'ship',
 'ship',
 'dog',
 'frog',
 'cat',
 'bird',
 'horse',
 'cat',
 'frog',
 'truck',
 'frog',
 'bird',
 'automobile',
 'bird',
 'cat',
 'truck',
 'bird',
 'frog',
 'ship',
 'ship',
 'airplane',
 'bird',
 'truck',
 'cat',
 'cat',
 'ship',
 'ship',
 'automobile',
 'automobile',
 'dog',
 'bird',
 'horse',
 'cat',
 'ship',
 'ship',
 'truck',
 'airplane',
 'deer',
 'ship',
 'frog',
 'deer',
 'cat',
 'deer',
 'airplane',
 'airplane',
 'horse',
 'deer',
 'deer',
 'frog',
 

In [51]:
out=np.array(ypredlist)

In [57]:
import pandas as pd
res=pd.DataFrame(out)
res.to_csv('predict.csv',header=False,index=False)